### ISSUE TITLE
we should get only the chapter titles as the main links

### ISSUE THREAD

**Issue by tshrinivasan** [nifey/epub2sphinx#26]
Thanks for the great work.

Testing with this book.
https://freetamilebooks.com/ebooks/namma_ooru_kovai/

epub2sphinx -o out_dir -t alabaster namma_ooru_kovai.epub -b -s

There are too many "Front Page" test as links on index pages and side bar.

![image](https://user-images.githubusercontent.com/1268536/142302194-3013f248-43e7-41b8-9c92-11d62c4fd4e2.png)

we should get only the chapter titles as the main links.

Please explore on this.

**Comment by nifey** [comment]
As of now, the title is retrieved from the rubric of the converted ReST content. And if the title is not found in the content, we default to "Front page".

I did some searching about this. I find that we can reliably retrieve the chapter title from the NCX file.
I'll modify the tool to obtain the title names from the NCX file.

**Comment by nifey** [comment]
After [this commit](https://github.com/nifey/epub2sphinx/commit/50d4e2203292b40e12ef9bce5b979b52ff444922), the output for this book is as shown below:

![Screenshot 2021-11-19 at 20-32-24 நம்ம ஊரு கோவை — நம்ம ஊரு கோவை documentation](https://user-images.githubusercontent.com/20047982/142644759-e1f7d892-1f21-4a84-9e0f-41efb309547f.png)
 
There are still two unsolved issues here:
1. There are some chapters (usually at the beginning and end of some books) that don't have an entry in the NCX file and so we default to the "Front page" name for those chapters. We can maybe merge all unnamed chapters at the beginning and end of the book into one chapter.
2. Subsections are not handled properly. Here in this book, the "mall" section has some subsection but those are shown as separate sections at the same level.

**Comment by nifey** [comment]
Both of the above issues have been fixed in version 0.0.3.

The unnamed pages at the beginning would be merged into a single page named "Front Page".
And subchapters would be merged into one chapter.
